### PR TITLE
Add port number to node address to distinguish labels

### PR DESCRIPTION
**Pull request by Tenchi2xh**

### CODE REVIEW

**Comment by raboof** [comment]
Can we send this PR upstream, too?

**Comment by raboof** [comment]
Change seems reasonable AFAICS...

**Comment by Tenchi2xh** [comment]
I'll also PR the Prometheus guys then

**Comment by thomaskrag** [comment]
@bastichelaar Mind double checking this? Should be simple and it seems to be OK.

**Pull request merged**
